// Generated by the protocol buffer compiler.  DO NOT EDIT!

package bio.pih.io.proto;

public final class Io {
  private Io() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\010io.proto\022\005proto\"\313\001\n\016StoredDatabank\0220\n\004" +
      "type\030\001 \001(\0162\".proto.StoredDatabank.Sequen" +
      "ceType\022\024\n\014qtdSequences\030\002 \001(\005\022\020\n\010qtdBases" +
      "\030\003 \001(\003\0220\n\rsequencesInfo\030\004 \003(\0132\031.proto.St" +
      "oredSequenceInfo\"-\n\014SequenceType\022\007\n\003DNA\020" +
      "\000\022\007\n\003RNA\020\001\022\013\n\007PROTEIN\020\002\"@\n\022StoredSequenc" +
      "eInfo\022\n\n\002id\030\001 \001(\005\022\016\n\006offset\030\002 \001(\005\022\016\n\006len" +
      "gth\030\003 \001(\005\"\232\001\n\016StoredSequence\022\n\n\002id\030\001 \001(\005" +
      "\022\n\n\002gi\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\021\n\taccession\030" +
      "\004 \001(\t\022\023\n\013description\030\005 \001(\t\022\017\n\007version\030\006 " +
      "\001(\005\022\027\n\017encodedSequence\030\007 \001(\014\022\020\n\010sequence" +
      "\030\010 \001(\tB\026\n\020bio.pih.io.protoB\002Io";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"io.proto\".", e);
    }
  }
  
  public static final class StoredDatabank extends
      com.google.protobuf.GeneratedMessage {
    // Use StoredDatabank.newBuilder() to construct.
    private StoredDatabank() {}
    
    private static final StoredDatabank defaultInstance = new StoredDatabank();
    public static StoredDatabank getDefaultInstance() {
      return defaultInstance;
    }
    
    public StoredDatabank getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bio.pih.io.proto.Io.internal_static_proto_StoredDatabank_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bio.pih.io.proto.Io.internal_static_proto_StoredDatabank_fieldAccessorTable;
    }
    
    public static enum SequenceType {
      DNA(0, 0),
      RNA(1, 1),
      PROTEIN(2, 2),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static SequenceType valueOf(int value) {
        switch (value) {
          case 0: return DNA;
          case 1: return RNA;
          case 2: return PROTEIN;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return bio.pih.io.proto.Io.StoredDatabank.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final SequenceType[] VALUES = {
        DNA, RNA, PROTEIN, 
      };
      public static SequenceType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private SequenceType(int index, int value) {
        this.index = index;
        this.value = value;
      }
    }
    
    // optional .proto.StoredDatabank.SequenceType type = 1;
    private boolean hasType;
    private bio.pih.io.proto.Io.StoredDatabank.SequenceType type_ = bio.pih.io.proto.Io.StoredDatabank.SequenceType.DNA;
    public boolean hasType() { return hasType; }
    public bio.pih.io.proto.Io.StoredDatabank.SequenceType getType() { return type_; }
    
    // optional int32 qtdSequences = 2;
    private boolean hasQtdSequences;
    private int qtdSequences_ = 0;
    public boolean hasQtdSequences() { return hasQtdSequences; }
    public int getQtdSequences() { return qtdSequences_; }
    
    // optional int64 qtdBases = 3;
    private boolean hasQtdBases;
    private long qtdBases_ = 0L;
    public boolean hasQtdBases() { return hasQtdBases; }
    public long getQtdBases() { return qtdBases_; }
    
    // repeated .proto.StoredSequenceInfo sequencesInfo = 4;
    private java.util.List<bio.pih.io.proto.Io.StoredSequenceInfo> sequencesInfo_ =
      java.util.Collections.emptyList();
    public java.util.List<bio.pih.io.proto.Io.StoredSequenceInfo> getSequencesInfoList() {
      return sequencesInfo_;
    }
    public int getSequencesInfoCount() { return sequencesInfo_.size(); }
    public bio.pih.io.proto.Io.StoredSequenceInfo getSequencesInfo(int index) {
      return sequencesInfo_.get(index);
    }
    
    public static bio.pih.io.proto.Io.StoredDatabank parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredDatabank parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredDatabank parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredDatabank parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredDatabank parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredDatabank parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredDatabank parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredDatabank parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(bio.pih.io.proto.Io.StoredDatabank prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using bio.pih.io.proto.Io.StoredDatabank.newBuilder()
      private Builder() {}
      
      bio.pih.io.proto.Io.StoredDatabank result = new bio.pih.io.proto.Io.StoredDatabank();
      
      protected bio.pih.io.proto.Io.StoredDatabank internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new bio.pih.io.proto.Io.StoredDatabank();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bio.pih.io.proto.Io.StoredDatabank.getDescriptor();
      }
      
      public bio.pih.io.proto.Io.StoredDatabank getDefaultInstanceForType() {
        return bio.pih.io.proto.Io.StoredDatabank.getDefaultInstance();
      }
      
      public bio.pih.io.proto.Io.StoredDatabank build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private bio.pih.io.proto.Io.StoredDatabank buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public bio.pih.io.proto.Io.StoredDatabank buildPartial() {
        if (result.sequencesInfo_ != java.util.Collections.EMPTY_LIST) {
          result.sequencesInfo_ =
            java.util.Collections.unmodifiableList(result.sequencesInfo_);
        }
        bio.pih.io.proto.Io.StoredDatabank returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional .proto.StoredDatabank.SequenceType type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public bio.pih.io.proto.Io.StoredDatabank.SequenceType getType() {
        return result.getType();
      }
      public Builder setType(bio.pih.io.proto.Io.StoredDatabank.SequenceType value) {
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = bio.pih.io.proto.Io.StoredDatabank.SequenceType.DNA;
        return this;
      }
      
      // optional int32 qtdSequences = 2;
      public boolean hasQtdSequences() {
        return result.hasQtdSequences();
      }
      public int getQtdSequences() {
        return result.getQtdSequences();
      }
      public Builder setQtdSequences(int value) {
        result.hasQtdSequences = true;
        result.qtdSequences_ = value;
        return this;
      }
      public Builder clearQtdSequences() {
        result.hasQtdSequences = false;
        result.qtdSequences_ = 0;
        return this;
      }
      
      // optional int64 qtdBases = 3;
      public boolean hasQtdBases() {
        return result.hasQtdBases();
      }
      public long getQtdBases() {
        return result.getQtdBases();
      }
      public Builder setQtdBases(long value) {
        result.hasQtdBases = true;
        result.qtdBases_ = value;
        return this;
      }
      public Builder clearQtdBases() {
        result.hasQtdBases = false;
        result.qtdBases_ = 0L;
        return this;
      }
      
      // repeated .proto.StoredSequenceInfo sequencesInfo = 4;
      public java.util.List<bio.pih.io.proto.Io.StoredSequenceInfo> getSequencesInfoList() {
        return java.util.Collections.unmodifiableList(result.sequencesInfo_);
      }
      public int getSequencesInfoCount() {
        return result.getSequencesInfoCount();
      }
      public bio.pih.io.proto.Io.StoredSequenceInfo getSequencesInfo(int index) {
        return result.getSequencesInfo(index);
      }
      public Builder setSequencesInfo(int index, bio.pih.io.proto.Io.StoredSequenceInfo value) {
        result.sequencesInfo_.set(index, value);
        return this;
      }
      public Builder setSequencesInfo(int index, bio.pih.io.proto.Io.StoredSequenceInfo.Builder builderForValue) {
        result.sequencesInfo_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSequencesInfo(bio.pih.io.proto.Io.StoredSequenceInfo value) {
        if (result.sequencesInfo_.isEmpty()) {
          result.sequencesInfo_ = new java.util.ArrayList<bio.pih.io.proto.Io.StoredSequenceInfo>();
        }
        result.sequencesInfo_.add(value);
        return this;
      }
      public Builder addSequencesInfo(bio.pih.io.proto.Io.StoredSequenceInfo.Builder builderForValue) {
        if (result.sequencesInfo_.isEmpty()) {
          result.sequencesInfo_ = new java.util.ArrayList<bio.pih.io.proto.Io.StoredSequenceInfo>();
        }
        result.sequencesInfo_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSequencesInfo(
          java.lang.Iterable<? extends bio.pih.io.proto.Io.StoredSequenceInfo> values) {
        if (result.sequencesInfo_.isEmpty()) {
          result.sequencesInfo_ = new java.util.ArrayList<bio.pih.io.proto.Io.StoredSequenceInfo>();
        }
        super.addAll(values, result.sequencesInfo_);
        return this;
      }
      public Builder clearSequencesInfo() {
        result.sequencesInfo_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  public static final class StoredSequenceInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use StoredSequenceInfo.newBuilder() to construct.
    private StoredSequenceInfo() {}
    
    private static final StoredSequenceInfo defaultInstance = new StoredSequenceInfo();
    public static StoredSequenceInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public StoredSequenceInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bio.pih.io.proto.Io.internal_static_proto_StoredSequenceInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bio.pih.io.proto.Io.internal_static_proto_StoredSequenceInfo_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional int32 offset = 2;
    private boolean hasOffset;
    private int offset_ = 0;
    public boolean hasOffset() { return hasOffset; }
    public int getOffset() { return offset_; }
    
    // optional int32 length = 3;
    private boolean hasLength;
    private int length_ = 0;
    public boolean hasLength() { return hasLength; }
    public int getLength() { return length_; }
    
    public static bio.pih.io.proto.Io.StoredSequenceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequenceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequenceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequenceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequenceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequenceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequenceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequenceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(bio.pih.io.proto.Io.StoredSequenceInfo prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using bio.pih.io.proto.Io.StoredSequenceInfo.newBuilder()
      private Builder() {}
      
      bio.pih.io.proto.Io.StoredSequenceInfo result = new bio.pih.io.proto.Io.StoredSequenceInfo();
      
      protected bio.pih.io.proto.Io.StoredSequenceInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new bio.pih.io.proto.Io.StoredSequenceInfo();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bio.pih.io.proto.Io.StoredSequenceInfo.getDescriptor();
      }
      
      public bio.pih.io.proto.Io.StoredSequenceInfo getDefaultInstanceForType() {
        return bio.pih.io.proto.Io.StoredSequenceInfo.getDefaultInstance();
      }
      
      public bio.pih.io.proto.Io.StoredSequenceInfo build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private bio.pih.io.proto.Io.StoredSequenceInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public bio.pih.io.proto.Io.StoredSequenceInfo buildPartial() {
        bio.pih.io.proto.Io.StoredSequenceInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional int32 offset = 2;
      public boolean hasOffset() {
        return result.hasOffset();
      }
      public int getOffset() {
        return result.getOffset();
      }
      public Builder setOffset(int value) {
        result.hasOffset = true;
        result.offset_ = value;
        return this;
      }
      public Builder clearOffset() {
        result.hasOffset = false;
        result.offset_ = 0;
        return this;
      }
      
      // optional int32 length = 3;
      public boolean hasLength() {
        return result.hasLength();
      }
      public int getLength() {
        return result.getLength();
      }
      public Builder setLength(int value) {
        result.hasLength = true;
        result.length_ = value;
        return this;
      }
      public Builder clearLength() {
        result.hasLength = false;
        result.length_ = 0;
        return this;
      }
    }
  }
  
  public static final class StoredSequence extends
      com.google.protobuf.GeneratedMessage {
    // Use StoredSequence.newBuilder() to construct.
    private StoredSequence() {}
    
    private static final StoredSequence defaultInstance = new StoredSequence();
    public static StoredSequence getDefaultInstance() {
      return defaultInstance;
    }
    
    public StoredSequence getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bio.pih.io.proto.Io.internal_static_proto_StoredSequence_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bio.pih.io.proto.Io.internal_static_proto_StoredSequence_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string gi = 2;
    private boolean hasGi;
    private java.lang.String gi_ = "";
    public boolean hasGi() { return hasGi; }
    public java.lang.String getGi() { return gi_; }
    
    // optional string name = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string accession = 4;
    private boolean hasAccession;
    private java.lang.String accession_ = "";
    public boolean hasAccession() { return hasAccession; }
    public java.lang.String getAccession() { return accession_; }
    
    // optional string description = 5;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional int32 version = 6;
    private boolean hasVersion;
    private int version_ = 0;
    public boolean hasVersion() { return hasVersion; }
    public int getVersion() { return version_; }
    
    // optional bytes encodedSequence = 7;
    private boolean hasEncodedSequence;
    private com.google.protobuf.ByteString encodedSequence_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasEncodedSequence() { return hasEncodedSequence; }
    public com.google.protobuf.ByteString getEncodedSequence() { return encodedSequence_; }
    
    // optional string sequence = 8;
    private boolean hasSequence;
    private java.lang.String sequence_ = "";
    public boolean hasSequence() { return hasSequence; }
    public java.lang.String getSequence() { return sequence_; }
    
    public static bio.pih.io.proto.Io.StoredSequence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bio.pih.io.proto.Io.StoredSequence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(bio.pih.io.proto.Io.StoredSequence prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using bio.pih.io.proto.Io.StoredSequence.newBuilder()
      private Builder() {}
      
      bio.pih.io.proto.Io.StoredSequence result = new bio.pih.io.proto.Io.StoredSequence();
      
      protected bio.pih.io.proto.Io.StoredSequence internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new bio.pih.io.proto.Io.StoredSequence();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bio.pih.io.proto.Io.StoredSequence.getDescriptor();
      }
      
      public bio.pih.io.proto.Io.StoredSequence getDefaultInstanceForType() {
        return bio.pih.io.proto.Io.StoredSequence.getDefaultInstance();
      }
      
      public bio.pih.io.proto.Io.StoredSequence build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private bio.pih.io.proto.Io.StoredSequence buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public bio.pih.io.proto.Io.StoredSequence buildPartial() {
        bio.pih.io.proto.Io.StoredSequence returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string gi = 2;
      public boolean hasGi() {
        return result.hasGi();
      }
      public java.lang.String getGi() {
        return result.getGi();
      }
      public Builder setGi(java.lang.String value) {
        result.hasGi = true;
        result.gi_ = value;
        return this;
      }
      public Builder clearGi() {
        result.hasGi = false;
        result.gi_ = "";
        return this;
      }
      
      // optional string name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional string accession = 4;
      public boolean hasAccession() {
        return result.hasAccession();
      }
      public java.lang.String getAccession() {
        return result.getAccession();
      }
      public Builder setAccession(java.lang.String value) {
        result.hasAccession = true;
        result.accession_ = value;
        return this;
      }
      public Builder clearAccession() {
        result.hasAccession = false;
        result.accession_ = "";
        return this;
      }
      
      // optional string description = 5;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = "";
        return this;
      }
      
      // optional int32 version = 6;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public int getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(int value) {
        result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = 0;
        return this;
      }
      
      // optional bytes encodedSequence = 7;
      public boolean hasEncodedSequence() {
        return result.hasEncodedSequence();
      }
      public com.google.protobuf.ByteString getEncodedSequence() {
        return result.getEncodedSequence();
      }
      public Builder setEncodedSequence(com.google.protobuf.ByteString value) {
        result.hasEncodedSequence = true;
        result.encodedSequence_ = value;
        return this;
      }
      public Builder clearEncodedSequence() {
        result.hasEncodedSequence = false;
        result.encodedSequence_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // optional string sequence = 8;
      public boolean hasSequence() {
        return result.hasSequence();
      }
      public java.lang.String getSequence() {
        return result.getSequence();
      }
      public Builder setSequence(java.lang.String value) {
        result.hasSequence = true;
        result.sequence_ = value;
        return this;
      }
      public Builder clearSequence() {
        result.hasSequence = false;
        result.sequence_ = "";
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StoredDatabank_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_StoredDatabank_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_proto_StoredDatabank_descriptor,
          new java.lang.String[] { "Type", "QtdSequences", "QtdBases", "SequencesInfo", },
          bio.pih.io.proto.Io.StoredDatabank.class,
          bio.pih.io.proto.Io.StoredDatabank.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StoredSequenceInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_StoredSequenceInfo_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_proto_StoredSequenceInfo_descriptor,
          new java.lang.String[] { "Id", "Offset", "Length", },
          bio.pih.io.proto.Io.StoredSequenceInfo.class,
          bio.pih.io.proto.Io.StoredSequenceInfo.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StoredSequence_descriptor =
      getDescriptor().getMessageTypes().get(2);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_StoredSequence_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_proto_StoredSequence_descriptor,
          new java.lang.String[] { "Id", "Gi", "Name", "Accession", "Description", "Version", "EncodedSequence", "Sequence", },
          bio.pih.io.proto.Io.StoredSequence.class,
          bio.pih.io.proto.Io.StoredSequence.Builder.class);
}
